;Each new term in the Fibonacci sequence is generated by adding the previous two terms. By starting with 1 and 2, the first 10 terms will be:

;1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...

;By considering the terms in the Fibonacci sequence whose values do not exceed four million, find the sum of the even-valued terms.

$a = 1
$b = 1
$c = 0
$sum = 0

While $a < 4000000
	$c = $a + $b
	$b = $c + $a
	$a = $b + $c
	If mod($a,2) = 0 Then
		$sum += $a
	EndIf
	if Mod($b,2) = 0 Then
		$sum += $b
	EndIf
	If mod($c,2) = 0 Then
		$sum +=  $c
	EndIf
WEnd

MsgBox(0, "Answer", "The Answer is: "& $sum)
